debug: 1  # Debug 레벨 (0-4)

device: /dev/ttyGPS1
frame_id: gps

# 시리얼 통신 설정
uart1:
  baudrate: 115200  # 사용 가능한 baud rate로 변경 가능 (9600, 38400, 57600, 115200 등)

# Enable u-blox message publishers
publish:
  all: false
  nav:
    all: true
    relposned: true
    posllh: true
    posecef: true

subscribe:
  all: false
  rxm:
    all: true
  nav:
    all: true
  rtcm:
    all: true  # RTCM 메시지 구독 활성화

rtcm:
  enable: true